version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2002Project
  gitServerName: rimaSC
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: JMSTest
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
services:
- serviceName: project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_2002.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.siqa_git_2002.integrations:JMSFlowTest
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.siqa_git_2002.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_2002.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_2002.integrations:SSL_JDBC_test
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_git_2002.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_2002Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
configurationVariables:
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : MySQL
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : 9.60.195.99
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MySQL
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : 9.46.196.248
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : siqatest
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : TestDriver
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : sa
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : TestDriver
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2002Project.project.siqa_git_2002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}X4QCAWgjWkTdMQvFA5XaqGmK1wuN3U1rA1B0VhuZoUw="
